version: "3.8"

services:
  # --- API GATEWAY ---
  gateway:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "${GATEWAY_PORT:-8080}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - product-service
    networks:
      - app-network
  # --- USER SERVICE ---
  user-db:
    image: postgres:15-alpine
    container_name: user-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${USER_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${USER_DB_NAME}"]
      interval: 5s
      timeout: 5s
    ports:
      - "${USER_DB_PORT:-5432}:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile.dev
    container_name: user-service
    volumes:
      - ./user-service:/app
    environment:
      DB_HOST: user-db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${USER_DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      user-db:
        condition: service_healthy
    networks:
      - app-network

  # --- PRODUCT SERVICE ---
  product-db:
    image: postgres:15-alpine
    container_name: product-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${PRODUCT_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${PRODUCT_DB_NAME}"]
      interval: 5s
      timeout: 5s
    ports:
      - "${PRODUCT_DB_PORT:-5433}:5432"
    volumes:
      - product_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile.dev
    container_name: product-service
    volumes:
      - ./product-service:/app
    environment:
      DB_HOST: product-db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${PRODUCT_DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      product-db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  user_postgres_data:
  product_postgres_data:

networks:
  app-network:
    driver: bridge
