version: "3.8"

services:
  user-service:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./user-service:/app

  product-service:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./product-service:/app

  cart-service:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./cart-service:/app

  order-service:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./order-service:/app

  user-db:
    ports:
      - "${USER_DB_PORT:-5432}:5432"

  product-db:
    ports:
      - "${PRODUCT_DB_PORT:-5433}:5432"

  cart-redis:
    ports:
      - "${CART_REDIS_PORT:-6379}:6379"

  order-db:
    ports:
      - "${ORDER_DB_PORT:-5434}:5432"
