basePath: /api/v1
definitions:
  product-service_internal_domain.Category:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      products:
        description: Inverse association
        items:
          $ref: '#/definitions/product-service_internal_domain.Product'
        type: array
      updated_at:
        type: string
    required:
    - name
    type: object
  product-service_internal_domain.CategoryResponse:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  product-service_internal_domain.CategorySuccessResponse:
    properties:
      category:
        $ref: '#/definitions/product-service_internal_domain.Category'
      message:
        type: string
    type: object
  product-service_internal_domain.CreateProductRequest:
    properties:
      category_ids:
        description: User only sends [1, 2, 3]
        items:
          type: integer
        type: array
      description:
        type: string
      name:
        type: string
      price:
        type: integer
      stock:
        minimum: 0
        type: integer
    required:
    - category_ids
    - name
    - price
    - stock
    type: object
  product-service_internal_domain.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  product-service_internal_domain.PaginatedProducts:
    properties:
      limit:
        type: integer
      page:
        type: integer
      products:
        items:
          $ref: '#/definitions/product-service_internal_domain.ProductResponse'
        type: array
      total:
        type: integer
      total_pages:
        type: integer
    type: object
  product-service_internal_domain.Product:
    properties:
      categories:
        description: Many-to-Many association
        items:
          $ref: '#/definitions/product-service_internal_domain.Category'
        type: array
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: integer
      stock:
        minimum: 0
        type: integer
      updated_at:
        type: string
    required:
    - name
    - price
    - stock
    type: object
  product-service_internal_domain.ProductDataResponse:
    properties:
      product:
        $ref: '#/definitions/product-service_internal_domain.ProductResponse'
    type: object
  product-service_internal_domain.ProductResponse:
    properties:
      categories:
        items:
          $ref: '#/definitions/product-service_internal_domain.CategoryResponse'
        type: array
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: integer
      stock:
        type: integer
      updated_at:
        type: string
    type: object
  product-service_internal_domain.ProductSuccessResponse:
    properties:
      message:
        type: string
      product:
        $ref: '#/definitions/product-service_internal_domain.ProductResponse'
    type: object
  product-service_internal_domain.SuccessResponse:
    properties:
      message:
        type: string
    type: object
  product-service_internal_domain.UpdateProductRequest:
    properties:
      category_ids:
        description: If provided, we replace all categories
        items:
          type: integer
        type: array
      description:
        type: string
      name:
        type: string
      price:
        type: integer
      stock:
        minimum: 0
        type: integer
    type: object
host: localhost:8082
info:
  contact:
    email: renoaji25sep@gmail.com
    name: Septareno Nugroho Aji
  description: This is the product catalog and inventory management service for the
    e-commerce platform.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Product Service API
  version: "1.0"
paths:
  /categories:
    post:
      consumes:
      - application/json
      description: Create a new product category (Admin only)
      parameters:
      - description: Category data
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/product-service_internal_domain.Category'
      produces:
      - application/json
      responses:
        "201":
          description: Category created successfully
          schema:
            $ref: '#/definitions/product-service_internal_domain.CategorySuccessResponse'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/product-service_internal_domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/product-service_internal_domain.ErrorResponse'
        "403":
          description: 'Access denied: Admins only'
          schema:
            $ref: '#/definitions/product-service_internal_domain.ErrorResponse'
        "409":
          description: category already exists
          schema:
            $ref: '#/definitions/product-service_internal_domain.ErrorResponse'
        "500":
          description: could not create category
          schema:
            $ref: '#/definitions/product-service_internal_domain.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create a new category
      tags:
      - Categories
  /products:
    get:
      consumes:
      - application/json
      description: Get products with pagination and filters
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Items per page
        in: query
        name: limit
        type: integer
      - description: Search by product name
        in: query
        name: search
        type: string
      - description: Filter by category ID
        in: query
        name: category_id
        type: integer
      - description: Minimum price
        in: query
        name: min_price
        type: number
      - description: Maximum price
        in: query
        name: max_price
        type: number
      - default: created_at
        description: Sort field
        in: query
        name: sort_by
        type: string
      - default: desc
        description: Sort order (asc/desc)
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product-service_internal_domain.PaginatedProducts'
        "500":
          description: could not retrieve products
          schema:
            $ref: '#/definitions/product-service_internal_domain.ErrorResponse'
      summary: Get paginated products
      tags:
      - Products
    post:
      consumes:
      - application/json
      description: Create a new product (Admin only)
      parameters:
      - description: Product data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/product-service_internal_domain.CreateProductRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Product created successfully
          schema:
            $ref: '#/definitions/product-service_internal_domain.SuccessResponse'
        "400":
          description: Invalid request body / missing required fields / invalid category
            ID
          schema:
            $ref: '#/definitions/product-service_internal_domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/product-service_internal_domain.ErrorResponse'
        "403":
          description: 'Access denied: Admins only'
          schema:
            $ref: '#/definitions/product-service_internal_domain.ErrorResponse'
        "409":
          description: product already exists
          schema:
            $ref: '#/definitions/product-service_internal_domain.ErrorResponse'
        "500":
          description: could not create product
          schema:
            $ref: '#/definitions/product-service_internal_domain.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create a new product
      tags:
      - Products
  /products/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a product by ID (Admin only)
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Product deleted successfully
          schema:
            $ref: '#/definitions/product-service_internal_domain.SuccessResponse'
        "400":
          description: Invalid product ID
          schema:
            $ref: '#/definitions/product-service_internal_domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/product-service_internal_domain.ErrorResponse'
        "403":
          description: 'Access denied: Admins only'
          schema:
            $ref: '#/definitions/product-service_internal_domain.ErrorResponse'
        "404":
          description: product not found
          schema:
            $ref: '#/definitions/product-service_internal_domain.ErrorResponse'
        "500":
          description: could not delete product
          schema:
            $ref: '#/definitions/product-service_internal_domain.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Delete product
      tags:
      - Products
    get:
      consumes:
      - application/json
      description: Get a single product by its ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: product
          schema:
            $ref: '#/definitions/product-service_internal_domain.ProductDataResponse'
        "400":
          description: invalid product ID
          schema:
            $ref: '#/definitions/product-service_internal_domain.ErrorResponse'
        "404":
          description: product not found
          schema:
            $ref: '#/definitions/product-service_internal_domain.ErrorResponse'
        "500":
          description: could not retrieve product
          schema:
            $ref: '#/definitions/product-service_internal_domain.ErrorResponse'
      summary: Get product by ID
      tags:
      - Products
    put:
      consumes:
      - application/json
      description: Update product details (Admin only)
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: Product update data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/product-service_internal_domain.UpdateProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Product updated successfully
          schema:
            $ref: '#/definitions/product-service_internal_domain.ProductSuccessResponse'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/product-service_internal_domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/product-service_internal_domain.ErrorResponse'
        "403":
          description: 'Access denied: Admins only'
          schema:
            $ref: '#/definitions/product-service_internal_domain.ErrorResponse'
        "500":
          description: could not update product
          schema:
            $ref: '#/definitions/product-service_internal_domain.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update product
      tags:
      - Products
  /products/{id}/stock:
    patch:
      consumes:
      - application/json
      description: Add or remove product stock (Admin only)
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: Stock adjustment (positive to add, negative to remove)
        in: body
        name: stock
        required: true
        schema:
          properties:
            add:
              type: integer
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Stock updated successfully
          schema:
            $ref: '#/definitions/product-service_internal_domain.SuccessResponse'
        "400":
          description: Invalid product ID or request body
          schema:
            $ref: '#/definitions/product-service_internal_domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/product-service_internal_domain.ErrorResponse'
        "403":
          description: 'Access denied: Admins only'
          schema:
            $ref: '#/definitions/product-service_internal_domain.ErrorResponse'
        "409":
          description: Insufficient stock or product not found
          schema:
            $ref: '#/definitions/product-service_internal_domain.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update product stock
      tags:
      - Products
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
